// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/photogram-redesign/Discover.tsx": () => import("../components/mockups/photogram-redesign/Discover.tsx"),
  "./components/mockups/photogram-redesign/Feed.tsx": () => import("../components/mockups/photogram-redesign/Feed.tsx"),
  "./components/mockups/photogram-redesign/PostDetail.tsx": () => import("../components/mockups/photogram-redesign/PostDetail.tsx"),
  "./components/mockups/photogram-redesign/Profile.tsx": () => import("../components/mockups/photogram-redesign/Profile.tsx")
};
